Actualiza la versión de Go.
altipla-consulting/actools pull request #19
Opened 2021-11-10 19:45 UTC by luiighi2693

2021-11-10 20:05 UTC, ernestoalejo requested changes

2021-11-10 20:05 UTC, ernestoalejo commented on .github/workflows/release.yml
> +    - uses: altipla-consulting/altipla.actions/go-release-1.17.3@master
Esto no existe. Aparte no indicaríamos well patch. Apunta para crear esto antes de que podamos unir esto.

2021-11-11 11:09 UTC, luiighi2693 commented on .github/workflows/release.yml
> +    - uses: altipla-consulting/altipla.actions/go-release-1.17.3@master
se revirtio esta linea

2021-11-11 11:32 UTC, ernestoalejo commented on .github/workflows/release.yml
> +    - uses: altipla-consulting/altipla.actions/go-release-1.17.3@master
Pero si la reviertes no estás haciendo nada en el commit de la actualización. Tenemos como te decía que crear esto antes de poder unir este commit.

2021-11-11 11:37 UTC, luiighi2693 commented on .github/workflows/release.yml
> +    - uses: altipla-consulting/altipla.actions/go-release-1.17.3@master
Se creo en este PR -> https://github.com/altipla-consulting/altipla.actions/pull/1 y ajustare el commit, corrigiendo el fallo

2021-11-11 20:32 UTC, ernestoalejo approved these changes

2021-11-11 20:32 UTC, merged